FROM node:20-alpine AS builder

WORKDIR /app
COPY package.json package-lock.json* tsconfig.json ./
COPY packages/ ./packages/
COPY apps/web/ ./apps/web/

RUN npm install
RUN npm run build --workspace=@alpha/web

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
COPY --from=builder /app ./

EXPOSE 3000
CMD ["npm", "run", "start", "--workspace=@alpha/web"]
