FROM node:20-alpine AS builder

WORKDIR /app
COPY package.json package-lock.json* tsconfig.json ./
COPY packages/ ./packages/
COPY apps/admin/ ./apps/admin/

RUN npm install
RUN npm run build --workspace=@alpha/admin

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3001
ENV HOSTNAME="0.0.0.0"
COPY --from=builder /app ./

EXPOSE 3001
CMD ["npm", "run", "start", "--workspace=@alpha/admin"]
